services:
  mysql:
    container_name: some-mysql
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        PMA_HOST: ${DB_SERVER}
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - 8081:80
      networks:
        - prestashop_network

  prestashop:
    container_name: prestashop
    build:
      context: .
      dockerfile: ./Docker/prestashop/Dockerfile
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_ROOT_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}
      PS_INSTALL_AUTO: 1
      PS_ERASE_DB: ${PS_ERASE_DB}
      PS_INSTALL_DB: ${PS_INSTALL_DB}
      PS_DOMAIN: ${PS_DOMAIN}
      PS_LANGUAGE: ${PS_LANGUAGE}
      PS_COUNTRY: ${PS_COUNTRY}
      PS_ALL_LANGUAGES: 0
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
      ADMIN_MAIL: ${PS_ADMIN_MAIL}
      ADMIN_PASSWD: ${PS_ADMIN_PASSWD}
      PS_ENABLE_SSL: ${PS_SSL}
      PS_HANDLE_DYNAMIC_DOMAIN: 0
      PS_DEMO_MODE: 0
      PS_INSTALL_FIXTURES: ${PS_INSTALL_FIXTURES}
    networks:
      - prestashop_network
    volumes:
      - ./src:/var/www/html

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - prestashop
    ports:
      - "80:80"
      - "443:443"
    networks:
      - prestashop_network
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./src:/var/www/html:ro

networks:
  prestashop_network:
volumes:
  dbdata:
  