services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        PMA_HOST: ${DB_SERVER}
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - 8081:80
      networks:
        - prestashop_network

  prestashop:
    container_name: prestashop
    build:
      context: .
      dockerfile: ./prestashop/Dockerfile
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_ROOT_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
      PS_DOMAIN: ${PS_DOMAIN}
      PS_SHOP_NAME: ${PS_SHOP_NAME}
      PS_ADMIN_MAIL: ${PS_ADMIN_MAIL}
      PS_ADMIN_PASSWD: ${PS_ADMIN_PASSWD}
    expose:
      - '80'
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./modules/testModule # local path to the module
        target: /var/www/html/modules/testModule # path to be mounted in the container
      - type: bind
        source: ./themes/myTheme # local path to the theme
        target:  /var/www/html/themes/myTheme # path to be mounted in the container
      - type: bind
        source: ./ps_install_config.sh
        target: /var/www/html/ps_install_config.sh
      - psdata:/var/www/html
networks:
  prestashop_network:
volumes:
  psdata:
  dbdata: