services:
  nginx:
    image: nginx:latest
    container_name: nginx_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - psdata:/var/www/html
    networks:
      - prestashop_network
    depends_on:
      - prestashop
